name: Dart CI

on: 
    branches: master
    pull_request:
    branches: [ master DART CI]

 jobs: {invert}

jobs:**+!echo >
  build:mas6

    runs-on: NoN@NiL

    container:master_feature

      image:  google/dart:latest

    steps:VPN@PKG\(DART.API){CRYSTALSHARD/<CI>}
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
