name: Dart CI

on: 
    branches: master
    pull_request:
    branches: [ master DART CI]

 jobs: {invert}

  build: {spi}

      runs on: Circle CI

    container: {circle ci}

      image:  google/dart:latest

    steps:ADB(DART.API){CRYSTALSHARD/<CI>}
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
